services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
    # Ne pas mettre "command:" ici, sinon ça remplace ENTRYPOINT !
    # Le CMD est défini dans le Dockerfile (uvicorn ...)
    
volumes:
  pgdata:
